### ISSUE TITLE
Polymer 3 Support (AKA ES module support)

### ISSUE THREAD

**Issue by rjsteinert** [LostInBrittany/granite-qrcode-scanner#14]
Hi there - Great component! I've been scanning QR codes no problem with it. Any plans to upgrade it to be an ES module published on npm?

**Comment by abidhkm** [comment]
is it available for npm project now ?

**Comment by LostInBrittany** [comment]
Next week I will update this and other components to lit-element and they
will be on NPM registry.

**Comment by LostInBrittany** [comment]
Working on it, migrating LostInBrittany/granite-qrcode-decoder and LostInBrittany/granite-app-media-periodic-image-capture that are dependencies of this one...

**Comment by derhuebiii** [comment]
Thank you for your work! :)

**Comment by rjsteinert** [comment]
I haven't had a chance to try it yet but it looks like you published the Lit Element based version of this package. Good to close on this issue?

**Comment by LostInBrittany** [comment]
Yes, the current version is based on Lit Element, so I think we can close this one :)
