### ISSUE TITLE
`polymer-hybrid` branch doesn't seem to exist

### ISSUE THREAD

**Issue by davidmaxwaterman** [LostInBrittany/granite-qrcode-scanner#17]
see https://github.com/LostInBrittany/granite-qrcode-decoder/issues/2

**Comment by LostInBrittany** [comment]
Oups, I forgot to push one of the branches. 
Right now there are:
- [Polymer 1.x-hybrid](https://github.com/LostInBrittany/granite-qrcode-scanner/tree/polymer-1.x-hybrid)
-  [Polymer 2.x-hybrid](https://github.com/LostInBrittany/granite-qrcode-decoder/tree/polymer-hybrid)
