### ISSUE TITLE
The canvas does not work correctly

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [LostInBrittany/granite-qrcode-scanner#5]
Hello!

I don't know if it is a bug, a bad use or a misunderstand of the web component. 

When I set attributes `width` and `height` they are not used by the canvas.

You can see the code here: https://github.com/FlorentinDUBOIS/achievements/blob/master/ui/src/camera/camera.component.vue

Sincerely

**Comment by LostInBrittany** [comment]
hmmmmmm, good question... I will look at it! (ping me if you get no answer by tomorrow...)

**Comment by LostInBrittany** [comment]
It has been fixed on release 1.7.x
